### ISSUE TITLE
Add integration with GitHub Actions CI/CD

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-OlenaEfymenko#14]
Please configure integration with GitHub Actions CI/CD:
* [x] Create a new branch called `features/14-gha-ci-cd-integration` and do all the following steps within that branch.
* [x] Add `.github/workflows/ci.yml` running `pre-commit`. Set it up to run Python 3.11 env. Ensure you install `pre-commit` before running tests:
```yaml
---

name: 🧪

on:
  push:
  pull_request:

jobs:
  linters:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch the src
      uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install pre-commit
      run: python -m pip install --upgrade pre-commit

    - name: Run pre-commit
      run: python -m pre_commit run --all-files
      env:
        SKIP: no-commit-to-branch

...
```
* [x] Add GitHub Actions CI/CD badge (`main` branch) to `README.md` with a separate commit. (`[![🧪 CI/CD](https://github.com/kpi-web-guild/OlenaEfymenko/actions/workflows/ci.yml/badge.svg)](https://github.com/kpi-web-guild/django-girls-blog-OlenaEfymenko/actions/workflows/tox.yml?query=branch%3Amain)`)
* [x] Push the branch and create a Pull Request for it.
